services:
  testapp:
    image: testapp:1.0
    container_name: testapp
    links:
      - postgres
    # Comment out ports to prevent external access
    ports:
      - 8885:8885
    entrypoint: "./main"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-bullseye
    container_name: testapp-postgresql
    env_file:
      - ".env"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - "5456:5456"
    volumes:
      # - ./postgresql.conf:/var/lib/postgresql@16.9/data/postgresql.conf
      - postgres:/var/lib/postgresql@16.9/data
    command: -p 5456
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p 5456"]
      interval: 5s
      retries: 5
      start_period: 30s
      timeout: 5s  
    restart: unless-stopped

volumes:
  postgres:
    driver: local